<?php

namespace Database\Seeders;

use App\Models\InventoryItem;
use Illuminate\Database\Seeder;

class InventorySeeder extends Seeder
{
    public function run(): void
    {
        $items = [
            // ==================== EQUIPMENT / TOOLS ====================
            [
                'name' => 'Sony A7IV Camera',
                'category' => 'equipment',
                'description' => 'Full-frame mirrorless camera for photo and video.',
                'quantity' => 3,
                'unit' => 'units',
                'condition_status' => 'good',
                'availability_status' => 'available',
            ],
            [
                'name' => 'Canon EOS R5 Camera',
                'category' => 'equipment',
                'description' => 'High-resolution mirrorless camera for stills and 8K video.',
                'quantity' => 2,
                'unit' => 'units',
                'condition_status' => 'new',
                'availability_status' => 'available',
            ],
            [
                'name' => 'Sony 24-70mm f/2.8 Lens',
                'category' => 'equipment',
                'description' => 'Versatile zoom lens for portraits and events.',
                'quantity' => 3,
                'unit' => 'pcs',
                'condition_status' => 'good',
                'availability_status' => 'available',
            ],
            [
                'name' => 'Sony 70-200mm f/2.8 Lens',
                'category' => 'equipment',
                'description' => 'Telephoto lens for ceremony and candid shots.',
                'quantity' => 2,
                'unit' => 'pcs',
                'condition_status' => 'good',
                'availability_status' => 'available',
            ],
            [
                'name' => 'Sony 35mm f/1.4 Lens',
                'category' => 'equipment',
                'description' => 'Prime lens for cinematic low-light footage.',
                'quantity' => 2,
                'unit' => 'pcs',
                'condition_status' => 'good',
                'availability_status' => 'available',
            ],
            [
                'name' => 'DJI Mavic 3 Pro Drone',
                'category' => 'equipment',
                'description' => 'Professional drone for aerial cinematography.',
                'quantity' => 1,
                'unit' => 'units',
                'condition_status' => 'good',
                'availability_status' => 'available',
            ],
            [
                'name' => 'DJI RS 3 Gimbal Stabilizer',
                'category' => 'equipment',
                'description' => '3-axis gimbal for smooth video tracking shots.',
                'quantity' => 2,
                'unit' => 'units',
                'condition_status' => 'good',
                'availability_status' => 'available',
            ],
            [
                'name' => 'Manfrotto 502AH Video Tripod',
                'category' => 'equipment',
                'description' => 'Heavy-duty fluid head tripod for stable shots.',
                'quantity' => 3,
                'unit' => 'sets',
                'condition_status' => 'good',
                'availability_status' => 'available',
            ],
            [
                'name' => 'Godox SL150II LED Light',
                'category' => 'equipment',
                'description' => 'Bi-color LED video light for indoor/outdoor lighting.',
                'quantity' => 4,
                'unit' => 'units',
                'condition_status' => 'good',
                'availability_status' => 'available',
            ],
            [
                'name' => 'Godox AD200 Pro Flash',
                'category' => 'equipment',
                'description' => 'Portable pocket flash for off-camera lighting.',
                'quantity' => 2,
                'unit' => 'units',
                'condition_status' => 'new',
                'availability_status' => 'available',
            ],
            [
                'name' => 'Rode VideoMic Pro+',
                'category' => 'equipment',
                'description' => 'On-camera shotgun microphone for clear audio.',
                'quantity' => 3,
                'unit' => 'pcs',
                'condition_status' => 'good',
                'availability_status' => 'available',
            ],
            [
                'name' => 'Zoom H6 Audio Recorder',
                'category' => 'equipment',
                'description' => 'Multi-track audio recorder for ceremonies and speeches.',
                'quantity' => 2,
                'unit' => 'units',
                'condition_status' => 'good',
                'availability_status' => 'available',
            ],
            [
                'name' => 'SanDisk 128GB CFexpress Card',
                'category' => 'equipment',
                'description' => 'High-speed memory card for 4K/8K video recording.',
                'quantity' => 8,
                'unit' => 'pcs',
                'condition_status' => 'new',
                'availability_status' => 'available',
            ],
            [
                'name' => 'Sony NP-FZ100 Battery',
                'category' => 'equipment',
                'description' => 'Rechargeable battery for Sony A7 series cameras.',
                'quantity' => 10,
                'unit' => 'pcs',
                'condition_status' => 'new',
                'availability_status' => 'available',
            ],
            [
                'name' => 'Atomos Ninja V Monitor',
                'category' => 'equipment',
                'description' => 'External monitor/recorder for focus assist and ProRes recording.',
                'quantity' => 2,
                'unit' => 'units',
                'condition_status' => 'good',
                'availability_status' => 'available',
            ],
            [
                'name' => 'MacBook Pro 16" M3',
                'category' => 'equipment',
                'description' => 'Editing laptop for same-day edit and on-site post-production.',
                'quantity' => 1,
                'unit' => 'units',
                'condition_status' => 'new',
                'availability_status' => 'available',
            ],
            [
                'name' => 'Samsung T7 2TB SSD',
                'category' => 'equipment',
                'description' => 'Portable SSD for file transfer and backup on-site.',
                'quantity' => 3,
                'unit' => 'pcs',
                'condition_status' => 'new',
                'availability_status' => 'available',
            ],

            // ==================== EVENT MATERIALS ====================
            [
                'name' => 'Muslin Backdrop (White)',
                'category' => 'material',
                'description' => 'Plain white backdrop for studio-style shots.',
                'quantity' => 2,
                'unit' => 'pcs',
                'condition_status' => 'good',
                'availability_status' => 'available',
            ],
            [
                'name' => 'Sequin Backdrop (Gold)',
                'category' => 'material',
                'description' => 'Gold sequin backdrop for photo booth and glam shots.',
                'quantity' => 1,
                'unit' => 'pcs',
                'condition_status' => 'good',
                'availability_status' => 'available',
            ],
            [
                'name' => 'Photo Booth Frame',
                'category' => 'material',
                'description' => 'Large decorative frame for photo booth.',
                'quantity' => 2,
                'unit' => 'sets',
                'condition_status' => 'good',
                'availability_status' => 'available',
            ],
            [
                'name' => 'Photo Booth Props Set',
                'category' => 'material',
                'description' => 'Hats, signs, glasses, and fun props for photo booth.',
                'quantity' => 3,
                'unit' => 'sets',
                'condition_status' => 'good',
                'availability_status' => 'available',
            ],
            [
                'name' => 'Wedding Props Set',
                'category' => 'material',
                'description' => 'Flowers, rings, ribbons, and wedding-themed props.',
                'quantity' => 2,
                'unit' => 'sets',
                'condition_status' => 'good',
                'availability_status' => 'available',
            ],
            [
                'name' => 'Premium Photo Album (20x30)',
                'category' => 'material',
                'description' => 'Hardcover layflat photo album for wedding highlights.',
                'quantity' => 5,
                'unit' => 'pcs',
                'condition_status' => 'new',
                'availability_status' => 'available',
            ],
            [
                'name' => 'Classic Photo Album (11x14)',
                'category' => 'material',
                'description' => 'Standard photo album for event packages.',
                'quantity' => 8,
                'unit' => 'pcs',
                'condition_status' => 'new',
                'availability_status' => 'available',
            ],
            [
                'name' => 'Photo Print Paper (A4 Glossy)',
                'category' => 'material',
                'description' => 'High-quality glossy photo paper for prints.',
                'quantity' => 200,
                'unit' => 'sheets',
                'condition_status' => 'new',
                'availability_status' => 'available',
            ],
            [
                'name' => 'Canvas Print Material',
                'category' => 'material',
                'description' => 'Canvas sheets for large-format wall prints.',
                'quantity' => 10,
                'unit' => 'pcs',
                'condition_status' => 'new',
                'availability_status' => 'available',
            ],
            [
                'name' => 'USB Drive (32GB)',
                'category' => 'material',
                'description' => 'Custom-branded USB drive for delivering final files.',
                'quantity' => 50,
                'unit' => 'pcs',
                'condition_status' => 'new',
                'availability_status' => 'available',
            ],
            [
                'name' => 'USB Drive (64GB)',
                'category' => 'material',
                'description' => 'Custom-branded USB drive for delivering final files.',
                'quantity' => 30,
                'unit' => 'pcs',
                'condition_status' => 'new',
                'availability_status' => 'available',
            ],
            [
                'name' => 'Gift Box Packaging',
                'category' => 'material',
                'description' => 'Packaging box for albums and USB delivery.',
                'quantity' => 15,
                'unit' => 'pcs',
                'condition_status' => 'new',
                'availability_status' => 'available',
            ],
            [
                'name' => 'Tissue Paper & Ribbon Set',
                'category' => 'material',
                'description' => 'Wrapping materials for deliverables.',
                'quantity' => 20,
                'unit' => 'sets',
                'condition_status' => 'new',
                'availability_status' => 'available',
            ],
            [
                'name' => 'Sticker Labels (Custom)',
                'category' => 'material',
                'description' => 'Branded stickers for packaging and USB drives.',
                'quantity' => 100,
                'unit' => 'pcs',
                'condition_status' => 'new',
                'availability_status' => 'available',
            ],
        ];

        foreach ($items as $item) {
            InventoryItem::updateOrCreate(
                ['name' => $item['name']],
                $item
            );
        }
    }
}
